export const data = [
  {
    id: 79364,
    name: "Lake Love",
    slug: "lake-love",
    permalink: "https://pattersonflynnmartin.com/product/lake-love/",
    date_created: "2021-03-16T10:48:09",
    date_created_gmt: "2021-03-16T14:48:09",
    date_modified: "2021-03-16T11:01:33",
    date_modified_gmt: "2021-03-16T15:01:33",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "76333",
    price: "",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 83, name: "PFM Signature", slug: "pfm-signature" }],
    tags: [
      {
        id: 6836,
        name: "abstract expressionist",
        slug: "abstract-expressionist",
      },
    ],
    images: [
      {
        id: 79366,
        date_created: "2021-03-16T07:01:14",
        date_created_gmt: "2021-03-16T15:01:14",
        date_modified: "2021-03-16T07:01:32",
        date_modified_gmt: "2021-03-16T15:01:32",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/76333.jpg",
        name: "76333",
        alt: "",
      },
      {
        id: 79366,
        date_created: "2021-03-16T07:01:14",
        date_created_gmt: "2021-03-16T15:01:14",
        date_modified: "2021-03-16T07:01:32",
        date_modified_gmt: "2021-03-16T15:01:32",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/76333.jpg",
        name: "76333",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 4,
        name: "Motif",
        position: 0,
        visible: true,
        variation: false,
        options: ["Abstract"],
      },
      {
        id: 5,
        name: "Product Type",
        position: 1,
        visible: true,
        variation: false,
        options: ["Custom"],
      },
      {
        id: 1,
        name: "Color",
        position: 2,
        visible: true,
        variation: false,
        options: ["Blue"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 3,
        visible: true,
        variation: false,
        options: ["Blue"],
      },
      {
        id: 8,
        name: "Fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool &amp; Silk"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 5,
        visible: true,
        variation: false,
        options: ["Wool Blends"],
      },
      {
        id: 3,
        name: "Construction",
        position: 6,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 15,
        name: "Construction &amp; Type",
        position: 7,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 8,
        visible: true,
        variation: false,
        options: ["1188"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "",
    related_ids: [4763, 4331, 4729, 4769, 4749],
    meta_data: [
      {
        id: 1738075,
        key: "type",
        value: {
          "pa_product-type": { "pa_product-type": "Custom" },
          "pa_construction-type": { "pa_construction-type": "Hand-Knotted" },
        },
      },
      {
        id: 1738097,
        key: "color",
        value: {
          pa_color: { pa_color: "Blue" },
          "pa_color-family": { "pa_color-family": "Blue" },
        },
      },
      { id: 1738099, key: "sku", value: "76333" },
      {
        id: 1738100,
        key: "fiber",
        value: {
          pa_fiber: { pa_fiber: "Wool & Silk" },
          "pa_filter-fiber": { "pa_filter-fiber": "Wool Blends" },
        },
      },
      { id: 1738131, key: "_tear_sheet", value: "field_5b2926346e3a5" },
      { id: 1738132, key: "tear_sheet", value: "79367" },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79364",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79362,
    name: "Moire",
    slug: "moire-3",
    permalink: "https://pattersonflynnmartin.com/product/moire-3/",
    date_created: "2021-03-16T10:47:03",
    date_created_gmt: "2021-03-16T14:47:03",
    date_modified: "2021-03-16T10:59:24",
    date_modified_gmt: "2021-03-16T14:59:24",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "64826",
    price: "",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 83, name: "PFM Signature", slug: "pfm-signature" }],
    tags: [
      {
        id: 6836,
        name: "abstract expressionist",
        slug: "abstract-expressionist",
      },
    ],
    images: [
      {
        id: 79365,
        date_created: "2021-03-16T06:58:54",
        date_created_gmt: "2021-03-16T14:58:54",
        date_modified: "2021-03-16T06:59:23",
        date_modified_gmt: "2021-03-16T14:59:23",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/64826.jpg",
        name: "64826",
        alt: "",
      },
      {
        id: 79365,
        date_created: "2021-03-16T06:58:54",
        date_created_gmt: "2021-03-16T14:58:54",
        date_modified: "2021-03-16T06:59:23",
        date_modified_gmt: "2021-03-16T14:59:23",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/64826.jpg",
        name: "64826",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 4,
        name: "Motif",
        position: 0,
        visible: true,
        variation: false,
        options: ["Abstract"],
      },
      {
        id: 5,
        name: "Product Type",
        position: 1,
        visible: true,
        variation: false,
        options: ["Custom"],
      },
      {
        id: 1,
        name: "Color",
        position: 2,
        visible: true,
        variation: false,
        options: ["Paradiso"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 3,
        visible: true,
        variation: false,
        options: ["Blue", "Grey"],
      },
      {
        id: 8,
        name: "Fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool &amp; Silk"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 5,
        visible: true,
        variation: false,
        options: ["Wool Blends"],
      },
      {
        id: 3,
        name: "Construction",
        position: 6,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 15,
        name: "Construction &amp; Type",
        position: 7,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 8,
        visible: true,
        variation: false,
        options: ["517"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "",
    related_ids: [4775, 4765, 4757, 4749, 4751],
    meta_data: [
      {
        id: 1738071,
        key: "type",
        value: {
          "pa_product-type": { "pa_product-type": "Custom" },
          "pa_construction-type": { "pa_construction-type": "Hand-Knotted" },
        },
      },
      {
        id: 1738083,
        key: "color",
        value: {
          pa_color: { pa_color: "Paradiso" },
          "pa_color-family": { "pa_color-family": "Blue, Grey" },
        },
      },
      { id: 1738085, key: "sku", value: "64826" },
      {
        id: 1738086,
        key: "fiber",
        value: {
          pa_fiber: { pa_fiber: "Wool & Silk" },
          "pa_filter-fiber": { "pa_filter-fiber": "Wool Blends" },
        },
      },
      { id: 1738127, key: "_tear_sheet", value: "field_5b2926346e3a5" },
      { id: 1738128, key: "tear_sheet", value: "79367" },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79362",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79361,
    name: "Waterfall",
    slug: "waterfall",
    permalink: "https://pattersonflynnmartin.com/product/waterfall/",
    date_created: "2021-03-16T10:46:53",
    date_created_gmt: "2021-03-16T14:46:53",
    date_modified: "2021-03-16T13:35:47",
    date_modified_gmt: "2021-03-16T17:35:47",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "68149",
    price: "",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 83, name: "PFM Signature", slug: "pfm-signature" }],
    tags: [
      {
        id: 6836,
        name: "abstract expressionist",
        slug: "abstract-expressionist",
      },
    ],
    images: [
      {
        id: 79392,
        date_created: "2021-03-16T09:35:35",
        date_created_gmt: "2021-03-16T17:35:35",
        date_modified: "2021-03-16T09:35:47",
        date_modified_gmt: "2021-03-16T17:35:47",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/68149.jpg",
        name: "68149",
        alt: "",
      },
      {
        id: 23289,
        date_created: "2018-07-05T14:17:00",
        date_created_gmt: "2018-07-05T18:17:00",
        date_modified: "2019-11-11T17:26:46",
        date_modified_gmt: "2019-11-11T21:26:46",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2017/05/06232927/68149_d.jpg",
        name: "68149_d",
        alt: "waterfall_wool-silk_hand-knotted_patterson-flynn-martin_pfm",
      },
    ],
    attributes: [
      {
        id: 4,
        name: "Motif",
        position: 0,
        visible: true,
        variation: false,
        options: ["Abstract"],
      },
      {
        id: 5,
        name: "Product Type",
        position: 1,
        visible: true,
        variation: false,
        options: ["Custom"],
      },
      {
        id: 1,
        name: "Color",
        position: 2,
        visible: true,
        variation: false,
        options: ["Earth &amp; Sky"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 3,
        visible: true,
        variation: false,
        options: ["Beige/Tan", "Purple"],
      },
      {
        id: 8,
        name: "Fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool &amp; Silk"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 5,
        visible: true,
        variation: false,
        options: ["Wool Blends"],
      },
      {
        id: 3,
        name: "Construction",
        position: 6,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 15,
        name: "Construction &amp; Type",
        position: 7,
        visible: true,
        variation: false,
        options: ["Hand-Knotted"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 8,
        visible: true,
        variation: false,
        options: ["1191"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "",
    related_ids: [4777, 4769, 4747, 4761, 4773],
    meta_data: [
      {
        id: 1738069,
        key: "type",
        value: {
          "pa_product-type": { "pa_product-type": "Custom" },
          "pa_construction-type": { "pa_construction-type": "Hand-Knotted" },
        },
      },
      {
        id: 1738076,
        key: "color",
        value: {
          pa_color: { pa_color: "Earth & Sky" },
          "pa_color-family": { "pa_color-family": "Beige/Tan, Purple" },
        },
      },
      { id: 1738078, key: "sku", value: "68149" },
      {
        id: 1738079,
        key: "fiber",
        value: {
          pa_fiber: { pa_fiber: "Wool & Silk" },
          "pa_filter-fiber": { "pa_filter-fiber": "Wool Blends" },
        },
      },
      { id: 1738125, key: "_tear_sheet", value: "field_5b2926346e3a5" },
      { id: 1738126, key: "tear_sheet", value: "79367" },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79361",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79326,
    name: "A Love Supreme",
    slug: "a-love-supreme-2",
    permalink: "https://pattersonflynnmartin.com/product/a-love-supreme-2/",
    date_created: "2021-03-15T13:18:11",
    date_created_gmt: "2021-03-15T17:18:11",
    date_modified: "2021-03-15T16:51:26",
    date_modified_gmt: "2021-03-15T20:51:26",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81460",
    price: "5700",
    regular_price: "5700",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "",
    dimensions: { length: "", width: "561578438", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: false,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 4887, name: "In-Stock", slug: "in-stock" }],
    tags: [],
    images: [
      {
        id: 79346,
        date_created: "2021-03-15T12:51:10",
        date_created_gmt: "2021-03-15T20:51:10",
        date_modified: "2021-03-15T12:51:25",
        date_modified_gmt: "2021-03-15T20:51:25",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_f-1-rotated.jpg",
        name: "80040_f",
        alt: "",
      },
      {
        id: 79312,
        date_created: "2021-03-15T06:22:28",
        date_created_gmt: "2021-03-15T14:22:28",
        date_modified: "2021-03-15T06:22:36",
        date_modified_gmt: "2021-03-15T14:22:36",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040.jpg",
        name: "80040",
        alt: "",
      },
      {
        id: 79313,
        date_created: "2021-03-15T06:23:06",
        date_created_gmt: "2021-03-15T14:23:06",
        date_modified: "2021-03-15T06:23:34",
        date_modified_gmt: "2021-03-15T14:23:34",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_d.jpg",
        name: "80040_d",
        alt: "",
      },
      {
        id: 79315,
        date_created: "2021-03-15T06:23:18",
        date_created_gmt: "2021-03-15T14:23:18",
        date_modified: "2021-03-15T06:23:34",
        date_modified_gmt: "2021-03-15T14:23:34",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_l.jpg",
        name: "80040_l",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Neutral and Ivory"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 1,
        visible: true,
        variation: false,
        options: ["Beige/Tan"],
      },
      {
        id: 4,
        name: "Motif",
        position: 2,
        visible: true,
        variation: false,
        options: ["Strie"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["1188"],
      },
      {
        id: 8,
        name: "Fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 5,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 3,
        name: "Construction",
        position: 6,
        visible: true,
        variation: false,
        options: ["Flatweave"],
      },
      {
        id: 15,
        name: "Construction &amp; Type",
        position: 7,
        visible: true,
        variation: false,
        options: ["Flatweave"],
      },
      {
        id: 6,
        name: "Size",
        position: 8,
        visible: true,
        variation: false,
        options: ["6' x 9'"],
      },
      {
        id: 16,
        name: "filter-size",
        position: 9,
        visible: true,
        variation: false,
        options: ["6' x 9'"],
      },
      {
        id: 5,
        name: "Product Type",
        position: 10,
        visible: true,
        variation: false,
        options: ["Custom"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>5,700.00</bdi></span>',
    related_ids: [12786, 25331, 27262, 16159, 25337],
    meta_data: [
      { id: 1735770, key: "_wp_page_template", value: "" },
      { id: 1735771, key: "_wf_ups_deliveryconfirmation", value: "0" },
      { id: 1735772, key: "_wf_ups_custom_declared_value", value: "" },
      { id: 1735773, key: "_wf_ups_hst", value: "" },
      { id: 1735774, key: "ph_ups_invoice_desc", value: "" },
      { id: 1735775, key: "_ph_ups_manufacture_country", value: "" },
      { id: 1735776, key: "_wf_ups_direct_delivery", value: "" },
      { id: 1735777, key: "_ph_ups_product_address_preference", value: "" },
      { id: 1735778, key: "_wf_pre_packed_product", value: "" },
      { id: 1735779, key: "_ph_ups_hazardous_materials", value: "no" },
      { id: 1735780, key: "_ph_ups_refrigeration", value: "" },
      { id: 1735781, key: "_ph_ups_restricted_article", value: "no" },
      { id: 1735797, key: "tear_sheet", value: "79316" },
      { id: 1735798, key: "_tear_sheet", value: "field_5b2926346e3a5" },
      { id: 1735799, key: "_", value: "field_5e768a31b9bf6" },
      { id: 1735800, key: "detail_image", value: "" },
      { id: 1735801, key: "_detail_image", value: "field_5ae0817867299" },
      { id: 1735802, key: "full_rug_image", value: "" },
      { id: 1735803, key: "_full_rug_image", value: "field_5ae081b16729a" },
      { id: 1735804, key: "artwork", value: "" },
      { id: 1735805, key: "_artwork", value: "field_5bfd53abc79eb" },
      { id: 1735806, key: "lifestyle_image", value: "" },
      { id: 1735807, key: "_lifestyle_image", value: "field_5cc3260810cd7" },
      { id: 1735808, key: "detail_image_2", value: "" },
      { id: 1735809, key: "_detail_image_2", value: "field_5cf1482c13900" },
      { id: 1735810, key: "sku", value: "81460" },
      {
        id: 1735812,
        key: "color",
        value:
          '{"pa_color":{"pa_color":"Neutral and Ivory"},"pa_color-family":{"pa_color-family":"Beige\\/Tan"}}',
      },
      { id: 1735813, key: "_color", value: "field_533e9f0a5c0a1" },
      { id: 1735814, key: "fiber", value: "Wool" },
      { id: 1735815, key: "_fiber", value: "field_533eb078ab7d3" },
      { id: 1735816, key: "construction", value: "" },
      { id: 1735817, key: "_construction", value: "field_5a709ba7ce9ba" },
      { id: 1735818, key: "more_info", value: "" },
      { id: 1735819, key: "_more_info", value: "field_5a8c9061d3c3c" },
      { id: 1735820, key: "colorfamily", value: "" },
      { id: 1735821, key: "_colorfamily", value: "field_5a79c5d7b380e" },
      { id: 1735822, key: "style", value: "" },
      { id: 1735823, key: "_style", value: "field_533ea09e693d9" },
      {
        id: 1735824,
        key: "type",
        value: { "pa_product-type": { "pa_product-type": "Custom" } },
      },
      { id: 1735825, key: "_type", value: "field_5343abaf925a2" },
      { id: 1735826, key: "category", value: "" },
      { id: 1735827, key: "_category", value: "field_54c7d296643c1" },
      { id: 1735828, key: "availability", value: "" },
      { id: 1735829, key: "_availability", value: "field_5a79c6725cbde" },
      { id: 1735830, key: "retail_price", value: "5,700" },
      { id: 1735831, key: "_retail_price", value: "field_5bd0c8f6931f6" },
      { id: 1735832, key: "full_rugs_size", value: "6' x 9'" },
      { id: 1735833, key: "_full_rugs_size", value: "field_5bd0c91e931f9" },
      { id: 1735834, key: "other_sizes", value: "" },
      { id: 1735835, key: "_other_sizes", value: "field_5b2bce9c9340e" },
      { id: 1735836, key: "texture", value: "" },
      { id: 1735837, key: "_texture", value: "field_533eae525b6a3" },
      { id: 1735838, key: "usage", value: "" },
      { id: 1735839, key: "_usage", value: "field_533eb20aab7d4" },
      { id: 1735840, key: "see_more", value: "" },
      { id: 1735841, key: "_see_more", value: "field_5b2bcb855b837" },
      { id: 1735842, key: "repeats", value: "NO" },
      { id: 1735843, key: "_repeats", value: "field_5bd0c900931f7" },
      { id: 1735844, key: "width", value: "" },
      { id: 1735846, key: "sourcebook_style", value: "" },
      { id: 1735847, key: "_sourcebook_style", value: "field_5d10dc946c8d5" },
      { id: 1735848, key: "content", value: "" },
      { id: 1735849, key: "_content", value: "field_5f6b7f71aa077" },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79326",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79311,
    name: "A Love Supreme",
    slug: "a-love-supreme",
    permalink: "https://pattersonflynnmartin.com/product/a-love-supreme/",
    date_created: "2021-03-15T10:27:37",
    date_created_gmt: "2021-03-15T14:27:37",
    date_modified: "2021-03-15T10:44:17",
    date_modified_gmt: "2021-03-15T14:44:17",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81460",
    price: "",
    regular_price: "",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: false,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: false,
    weight: "",
    dimensions: { length: "", width: "561578438", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: false,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 83, name: "PFM Signature", slug: "pfm-signature" }],
    tags: [],
    images: [
      {
        id: 79312,
        date_created: "2021-03-15T06:22:28",
        date_created_gmt: "2021-03-15T14:22:28",
        date_modified: "2021-03-15T06:22:36",
        date_modified_gmt: "2021-03-15T14:22:36",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040.jpg",
        name: "80040",
        alt: "",
      },
      {
        id: 79313,
        date_created: "2021-03-15T06:23:06",
        date_created_gmt: "2021-03-15T14:23:06",
        date_modified: "2021-03-15T06:23:34",
        date_modified_gmt: "2021-03-15T14:23:34",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_d.jpg",
        name: "80040_d",
        alt: "",
      },
      {
        id: 79314,
        date_created: "2021-03-15T06:23:11",
        date_created_gmt: "2021-03-15T14:23:11",
        date_modified: "2021-03-15T06:23:34",
        date_modified_gmt: "2021-03-15T14:23:34",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_f.jpg",
        name: "80040_f",
        alt: "",
      },
      {
        id: 79315,
        date_created: "2021-03-15T06:23:18",
        date_created_gmt: "2021-03-15T14:23:18",
        date_modified: "2021-03-15T06:23:34",
        date_modified_gmt: "2021-03-15T14:23:34",
        src:
          "https://pattersonflynnmartin.com/wp-content/uploads/2021/03/80040_l.jpg",
        name: "80040_l",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 1,
        name: "Color",
        position: 0,
        visible: true,
        variation: false,
        options: ["Neutral and Ivory"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 1,
        visible: true,
        variation: false,
        options: ["Beige/Tan"],
      },
      {
        id: 8,
        name: "Fiber",
        position: 2,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 3,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 3,
        name: "Construction",
        position: 4,
        visible: true,
        variation: false,
        options: ["Flatweave"],
      },
      {
        id: 15,
        name: "Construction &amp; Type",
        position: 5,
        visible: true,
        variation: false,
        options: ["Flatweave"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 6,
        visible: true,
        variation: false,
        options: ["1188"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Strie"],
      },
      {
        id: 5,
        name: "Product Type",
        position: 8,
        visible: true,
        variation: false,
        options: ["Custom"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html: "",
    related_ids: [4755, 4747, 4753, 4331, 4727],
    meta_data: [
      { id: 1735109, key: "_wp_page_template", value: "default" },
      { id: 1735110, key: "_wf_ups_deliveryconfirmation", value: "0" },
      { id: 1735111, key: "_wf_ups_custom_declared_value", value: "" },
      { id: 1735112, key: "_wf_ups_hst", value: "" },
      { id: 1735113, key: "ph_ups_invoice_desc", value: "" },
      { id: 1735114, key: "_ph_ups_manufacture_country", value: "" },
      { id: 1735115, key: "_wf_ups_direct_delivery", value: "" },
      { id: 1735116, key: "_ph_ups_product_address_preference", value: "" },
      { id: 1735117, key: "_wf_pre_packed_product", value: "" },
      { id: 1735118, key: "_ph_ups_hazardous_materials", value: "no" },
      { id: 1735119, key: "_ph_ups_refrigeration", value: "" },
      { id: 1735120, key: "_ph_ups_restricted_article", value: "no" },
      { id: 1735136, key: "tear_sheet", value: "79316" },
      { id: 1735137, key: "_tear_sheet", value: "field_5b2926346e3a5" },
      { id: 1735138, key: "_", value: "field_5e768a31b9bf6" },
      { id: 1735139, key: "detail_image", value: "" },
      { id: 1735140, key: "_detail_image", value: "field_5ae0817867299" },
      { id: 1735141, key: "full_rug_image", value: "" },
      { id: 1735142, key: "_full_rug_image", value: "field_5ae081b16729a" },
      { id: 1735143, key: "artwork", value: "" },
      { id: 1735144, key: "_artwork", value: "field_5bfd53abc79eb" },
      { id: 1735145, key: "lifestyle_image", value: "" },
      { id: 1735146, key: "_lifestyle_image", value: "field_5cc3260810cd7" },
      { id: 1735147, key: "detail_image_2", value: "" },
      { id: 1735148, key: "_detail_image_2", value: "field_5cf1482c13900" },
      { id: 1735149, key: "sku", value: "81460" },
      {
        id: 1735151,
        key: "color",
        value: { pa_color: { pa_color: "Neutral and Ivory" } },
      },
      { id: 1735152, key: "_color", value: "field_533e9f0a5c0a1" },
      {
        id: 1735153,
        key: "fiber",
        value: {
          pa_fiber: { pa_fiber: "Wool" },
          "pa_filter-fiber": { "pa_filter-fiber": "Wool" },
        },
      },
      { id: 1735154, key: "_fiber", value: "field_533eb078ab7d3" },
      { id: 1735155, key: "construction", value: "" },
      { id: 1735156, key: "_construction", value: "field_5a709ba7ce9ba" },
      { id: 1735157, key: "more_info", value: "" },
      { id: 1735158, key: "_more_info", value: "field_5a8c9061d3c3c" },
      { id: 1735159, key: "colorfamily", value: "" },
      { id: 1735160, key: "_colorfamily", value: "field_5a79c5d7b380e" },
      { id: 1735161, key: "style", value: "" },
      { id: 1735162, key: "_style", value: "field_533ea09e693d9" },
      {
        id: 1735163,
        key: "type",
        value: {
          "pa_construction-type": { "pa_construction-type": "Flatweave" },
          "pa_product-type": { "pa_product-type": "Custom" },
        },
      },
      { id: 1735164, key: "_type", value: "field_5343abaf925a2" },
      { id: 1735165, key: "category", value: "" },
      { id: 1735166, key: "_category", value: "field_54c7d296643c1" },
      { id: 1735167, key: "availability", value: "" },
      { id: 1735168, key: "_availability", value: "field_5a79c6725cbde" },
      { id: 1735169, key: "retail_price", value: "" },
      { id: 1735170, key: "_retail_price", value: "field_5bd0c8f6931f6" },
      { id: 1735171, key: "full_rugs_size", value: "" },
      { id: 1735172, key: "_full_rugs_size", value: "field_5bd0c91e931f9" },
      { id: 1735173, key: "other_sizes", value: "" },
      { id: 1735174, key: "_other_sizes", value: "field_5b2bce9c9340e" },
      { id: 1735175, key: "texture", value: "" },
      { id: 1735176, key: "_texture", value: "field_533eae525b6a3" },
      { id: 1735177, key: "usage", value: "" },
      { id: 1735178, key: "_usage", value: "field_533eb20aab7d4" },
      { id: 1735179, key: "see_more", value: "" },
      { id: 1735180, key: "_see_more", value: "field_5b2bcb855b837" },
      { id: 1735181, key: "repeats", value: "NO" },
      { id: 1735182, key: "_repeats", value: "field_5bd0c900931f7" },
      { id: 1735183, key: "width", value: "" },
      { id: 1735185, key: "sourcebook_style", value: "" },
      { id: 1735186, key: "_sourcebook_style", value: "field_5d10dc946c8d5" },
      { id: 1735187, key: "content", value: "" },
      { id: 1735188, key: "_content", value: "field_5f6b7f71aa077" },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79311",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79166,
    name: "JACKS RIGHT",
    slug: "jacks-right-2",
    permalink: "https://pattersonflynnmartin.com/product/jacks-right-2/",
    date_created: "2021-03-10T16:05:40",
    date_created_gmt: "2021-03-10T20:05:40",
    date_modified: "2021-03-10T17:07:33",
    date_modified_gmt: "2021-03-10T21:07:33",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81479",
    price: "0",
    regular_price: "0",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "8",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 78, name: "Broadloom", slug: "broadloom" }],
    tags: [{ id: 4176, name: "Cuttings", slug: "cuttings" }],
    images: [
      {
        id: 79251,
        date_created: "2021-03-10T12:24:13",
        date_created_gmt: "2021-03-10T20:24:13",
        date_modified: "2021-03-10T13:07:33",
        date_modified_gmt: "2021-03-10T21:07:33",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162426/81479.jpg",
        name: "81479",
        alt: "",
      },
      {
        id: 79251,
        date_created: "2021-03-10T12:24:13",
        date_created_gmt: "2021-03-10T20:24:13",
        date_modified: "2021-03-10T13:07:33",
        date_modified_gmt: "2021-03-10T21:07:33",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162426/81479.jpg",
        name: "81479",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 8,
        name: "Fiber",
        position: 0,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 1,
        name: "Color",
        position: 1,
        visible: true,
        variation: false,
        options: ["Greystone", "Silver", "White"],
      },
      {
        id: 10,
        name: "Width",
        position: 2,
        visible: true,
        variation: false,
        options: ["13'2\""],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["54"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 14,
        name: "filter-widths",
        position: 5,
        visible: true,
        variation: false,
        options: ["13'"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 6,
        visible: true,
        variation: false,
        options: ["Grey"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Checkered"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>0.00</bdi></span>',
    related_ids: [6837, 10556, 9941, 12196, 10578],
    meta_data: [
      { id: 1730024, key: "sku", value: "81479" },
      {
        id: 1730025,
        key: "fiber",
        value: { "pa_filter-fiber": { "pa_filter-fiber": "Wool" } },
      },
      {
        id: 1730622,
        key: "color",
        value: { "pa_color-family": { "pa_color-family": "Grey" } },
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79166",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79165,
    name: "JACKS RIGHT",
    slug: "jacks-right",
    permalink: "https://pattersonflynnmartin.com/product/jacks-right/",
    date_created: "2021-03-10T16:05:39",
    date_created_gmt: "2021-03-10T20:05:39",
    date_modified: "2021-03-10T17:07:33",
    date_modified_gmt: "2021-03-10T21:07:33",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81478",
    price: "0",
    regular_price: "0",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "8",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 78, name: "Broadloom", slug: "broadloom" }],
    tags: [{ id: 4176, name: "Cuttings", slug: "cuttings" }],
    images: [
      {
        id: 79252,
        date_created: "2021-03-10T12:24:15",
        date_created_gmt: "2021-03-10T20:24:15",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162424/81478.jpg",
        name: "81478",
        alt: "",
      },
      {
        id: 79252,
        date_created: "2021-03-10T12:24:15",
        date_created_gmt: "2021-03-10T20:24:15",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162424/81478.jpg",
        name: "81478",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 8,
        name: "Fiber",
        position: 0,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 1,
        name: "Color",
        position: 1,
        visible: true,
        variation: false,
        options: ["Charcoal", "Platinum", "Steel"],
      },
      {
        id: 10,
        name: "Width",
        position: 2,
        visible: true,
        variation: false,
        options: ["13'2\""],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["54"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 14,
        name: "filter-widths",
        position: 5,
        visible: true,
        variation: false,
        options: ["13'"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 6,
        visible: true,
        variation: false,
        options: ["Taupe"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Checkered"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>0.00</bdi></span>',
    related_ids: [6834, 6783, 10581, 11955, 10551],
    meta_data: [
      { id: 1730022, key: "sku", value: "81478" },
      {
        id: 1730023,
        key: "fiber",
        value: { "pa_filter-fiber": { "pa_filter-fiber": "Wool" } },
      },
      {
        id: 1730619,
        key: "color",
        value: { "pa_color-family": { "pa_color-family": "Taupe" } },
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79165",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79164,
    name: "TAWNY",
    slug: "tawny-5",
    permalink: "https://pattersonflynnmartin.com/product/tawny-5/",
    date_created: "2021-03-10T16:05:39",
    date_created_gmt: "2021-03-10T20:05:39",
    date_modified: "2021-03-10T17:07:32",
    date_modified_gmt: "2021-03-10T21:07:32",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81203",
    price: "0",
    regular_price: "0",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 2,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "8",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 78, name: "Broadloom", slug: "broadloom" }],
    tags: [{ id: 4176, name: "Cuttings", slug: "cuttings" }],
    images: [
      {
        id: 79249,
        date_created: "2021-03-10T12:24:10",
        date_created_gmt: "2021-03-10T20:24:10",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162428/81203.jpg",
        name: "81203",
        alt: "",
      },
      {
        id: 79249,
        date_created: "2021-03-10T12:24:10",
        date_created_gmt: "2021-03-10T20:24:10",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162428/81203.jpg",
        name: "81203",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 8,
        name: "Fiber",
        position: 0,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 1,
        name: "Color",
        position: 1,
        visible: true,
        variation: false,
        options: ["Sapphire"],
      },
      {
        id: 10,
        name: "Width",
        position: 2,
        visible: true,
        variation: false,
        options: ["13'2\""],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["54"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 14,
        name: "filter-widths",
        position: 5,
        visible: true,
        variation: false,
        options: ["13'"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 6,
        visible: true,
        variation: false,
        options: ["Blue"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Trellis"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>0.00</bdi></span>',
    related_ids: [16326, 9939, 16190, 10581, 11955],
    meta_data: [
      { id: 1730020, key: "sku", value: "81203" },
      {
        id: 1730021,
        key: "fiber",
        value: { "pa_filter-fiber": { "pa_filter-fiber": "Wool" } },
      },
      {
        id: 1730616,
        key: "color",
        value: { "pa_color-family": { "pa_color-family": "Blue" } },
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79164",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79163,
    name: "TAWNY",
    slug: "tawny-4",
    permalink: "https://pattersonflynnmartin.com/product/tawny-4/",
    date_created: "2021-03-10T16:05:39",
    date_created_gmt: "2021-03-10T20:05:39",
    date_modified: "2021-03-10T17:07:32",
    date_modified_gmt: "2021-03-10T21:07:32",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "81200",
    price: "0",
    regular_price: "0",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 1,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "8",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 78, name: "Broadloom", slug: "broadloom" }],
    tags: [{ id: 4176, name: "Cuttings", slug: "cuttings" }],
    images: [
      {
        id: 79250,
        date_created: "2021-03-10T12:24:11",
        date_created_gmt: "2021-03-10T20:24:11",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162427/81200.jpg",
        name: "81200",
        alt: "",
      },
      {
        id: 79250,
        date_created: "2021-03-10T12:24:11",
        date_created_gmt: "2021-03-10T20:24:11",
        date_modified: "2021-03-10T13:07:32",
        date_modified_gmt: "2021-03-10T21:07:32",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162427/81200.jpg",
        name: "81200",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 8,
        name: "Fiber",
        position: 0,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 1,
        name: "Color",
        position: 1,
        visible: true,
        variation: false,
        options: ["Pepper"],
      },
      {
        id: 10,
        name: "Width",
        position: 2,
        visible: true,
        variation: false,
        options: ["13'2\""],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["54"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 14,
        name: "filter-widths",
        position: 5,
        visible: true,
        variation: false,
        options: ["13'"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 6,
        visible: true,
        variation: false,
        options: ["Grey"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Trellis"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>0.00</bdi></span>',
    related_ids: [10578, 12182, 16326, 6837, 16190],
    meta_data: [
      { id: 1730018, key: "sku", value: "81200" },
      {
        id: 1730019,
        key: "fiber",
        value: { "pa_filter-fiber": { "pa_filter-fiber": "Wool" } },
      },
      {
        id: 1730613,
        key: "color",
        value: { "pa_color-family": { "pa_color-family": "Grey" } },
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79163",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
  {
    id: 79162,
    name: "WOVEN ROAD",
    slug: "woven-road",
    permalink: "https://pattersonflynnmartin.com/product/woven-road/",
    date_created: "2021-03-10T16:05:39",
    date_created_gmt: "2021-03-10T20:05:39",
    date_modified: "2021-03-10T17:07:20",
    date_modified_gmt: "2021-03-10T21:07:20",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "",
    short_description: "",
    sku: "68810",
    price: "0",
    regular_price: "0",
    sale_price: "",
    date_on_sale_from: null,
    date_on_sale_from_gmt: null,
    date_on_sale_to: null,
    date_on_sale_to_gmt: null,
    on_sale: false,
    purchasable: true,
    total_sales: 0,
    virtual: false,
    downloadable: false,
    downloads: [],
    download_limit: -1,
    download_expiry: -1,
    external_url: "",
    button_text: "",
    tax_status: "taxable",
    tax_class: "",
    manage_stock: false,
    stock_quantity: null,
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    sold_individually: true,
    weight: "8",
    dimensions: { length: "", width: "", height: "" },
    shipping_required: true,
    shipping_taxable: true,
    shipping_class: "",
    shipping_class_id: 0,
    reviews_allowed: true,
    average_rating: "0.00",
    rating_count: 0,
    upsell_ids: [],
    cross_sell_ids: [],
    parent_id: 0,
    purchase_note: "",
    categories: [{ id: 78, name: "Broadloom", slug: "broadloom" }],
    tags: [{ id: 4176, name: "Cuttings", slug: "cuttings" }],
    images: [
      {
        id: 79214,
        date_created: "2021-03-10T12:23:04",
        date_created_gmt: "2021-03-10T20:23:04",
        date_modified: "2021-03-10T13:07:20",
        date_modified_gmt: "2021-03-10T21:07:20",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162514/68810.jpg",
        name: "68810",
        alt: "",
      },
      {
        id: 79214,
        date_created: "2021-03-10T12:23:04",
        date_created_gmt: "2021-03-10T20:23:04",
        date_modified: "2021-03-10T13:07:20",
        date_modified_gmt: "2021-03-10T21:07:20",
        src:
          "https://pfm-website-images.s3.amazonaws.com/wp-content/uploads/2021/03/10162514/68810.jpg",
        name: "68810",
        alt: "",
      },
    ],
    attributes: [
      {
        id: 8,
        name: "Fiber",
        position: 0,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 1,
        name: "Color",
        position: 1,
        visible: true,
        variation: false,
        options: ["SANDHURST"],
      },
      {
        id: 10,
        name: "Width",
        position: 2,
        visible: true,
        variation: false,
        options: ["12'"],
      },
      {
        id: 12,
        name: "Group Number",
        position: 3,
        visible: true,
        variation: false,
        options: ["44"],
      },
      {
        id: 13,
        name: "filter-fiber",
        position: 4,
        visible: true,
        variation: false,
        options: ["Wool"],
      },
      {
        id: 14,
        name: "filter-widths",
        position: 5,
        visible: true,
        variation: false,
        options: ["12'"],
      },
      {
        id: 2,
        name: "Color Family",
        position: 6,
        visible: true,
        variation: false,
        options: ["Beige/Tan"],
      },
      {
        id: 4,
        name: "Motif",
        position: 7,
        visible: true,
        variation: false,
        options: ["Solid"],
      },
    ],
    default_attributes: [],
    variations: [],
    grouped_products: [],
    menu_order: 0,
    price_html:
      '<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">&#36;</span>0.00</bdi></span>',
    related_ids: [6834, 10919, 6783, 10584, 9944],
    meta_data: [
      { id: 1730016, key: "sku", value: "68810" },
      {
        id: 1730017,
        key: "fiber",
        value: { "pa_filter-fiber": { "pa_filter-fiber": "Wool" } },
      },
      {
        id: 1730610,
        key: "color",
        value: { "pa_color-family": { "pa_color-family": "Beige/Tan" } },
      },
    ],
    stock_status: "instock",
    _links: {
      self: [
        {
          href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products/79162",
        },
      ],
      collection: [
        { href: "https://pattersonflynnmartin.com/wp-json/wc/v3/products" },
      ],
    },
  },
];
